language: node_js

node_js:
  - "0.10"
before_install: 
 - npm install -g grunt-cli
install: 
 - npm install
before_script: 
 - grunt
script:
 - npm run-script grunt coveralls | ./node_modules/coveralls/bin/coveralls.js
